// PROTOTYPE — throwaway. Hardcoded, no error handling. Do not ship.
// GENERATED by `node scripts/xray.mjs --emit`. Do not edit — re-emit instead.
// Every selector below was compiled from a screenshot: vision named the control,
// geometry matched that name to a real DOM box. Zero model calls at runtime.
import { chromium } from 'patchright';

const ctx = await chromium.launchPersistentContext('E:\\eter-browser\\profiles\\agent', {
  channel: 'chrome', headless: false, args: ['--no-sandbox'],
  viewport: null, ignoreDefaultArgs: ['--enable-automation'],
});
const page = ctx.pages()[0] ?? (await ctx.newPage());

console.log('step: goto');
await page.goto('https://accounting.autocountcloud.com/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(7000);

if (page.url().includes('auth.')) {
  console.log('step: log in');
  await page.locator('body>div>div>div>div>div:nth-of-type(2)>div>div>div:nth-of-type(2)>div>div>div:nth-of-type(1)>div>form>div:nth-of-type(1)>div>div>div:nth-of-type(1)>input').fill('zhihong@eternalgy.me');
  await page.waitForTimeout(3000);
  await page.locator('body>div>div>div>div>div:nth-of-type(2)>div>div>div:nth-of-type(2)>div>div>div:nth-of-type(1)>div>form>div:nth-of-type(4)>div').click();
  await page.waitForTimeout(9000);
}

console.log('step: pick company');
await page.locator('body>div>div>div>div:nth-of-type(2)>div:nth-of-type(4)>div>div>div:nth-of-type(6)>div>div>div>div>table>tbody>tr:nth-of-type(1)>td:nth-of-type(1)>button').click();
await page.waitForTimeout(9000);

console.log('IN:', page.url(), '|', await page.title());
await ctx.close();
