// PROTOTYPE — throwaway. Hardcoded, no error handling. Do not ship.
//
// Lane 2 MVP (docs/recon-agent-2nd-lane-buildplan.md).
//   node scripts/xray.mjs              -> capture + vision + correlate + emit map
//   node scripts/xray.mjs --no-vision  -> load map, act by selector only, ZERO model calls
//
// Uses the `agent` profile: it is the only one with AutoCount's saved
// email+password, and filling the email makes Chrome autofill the password.

import fs from 'node:fs';
import { chromium } from 'patchright';

for (const l of fs.readFileSync('.env', 'utf8').split('\n')) {
  if (l.includes('=') && !l.startsWith('#')) process.env[l.slice(0, l.indexOf('=')).trim()] = l.slice(l.indexOf('=') + 1).trim();
}

const NO_VISION = process.argv.includes('--no-vision');
const LOGIN = process.argv.includes('--login'); // target the auth page, not Select Company
const PROFILE = 'E:\\eter-browser\\profiles\\agent';
// --url=<any page> points the lane at a different site. Without it, everything
// below behaves exactly as it did for AutoCount.
const ARG_URL = process.argv.find((a) => a.startsWith('--url='))?.slice(6);
const TARGET = ARG_URL ?? 'https://accounting.autocountcloud.com/';
const HOST = new URL(TARGET).hostname;
const MAP = ARG_URL ? `scripts/${HOST}.map.json`
  : LOGIN ? 'scripts/autocount-login.map.json' : 'scripts/autocount.map.json';
const SHOT = ARG_URL ? `scripts/xray-${HOST}.png`
  : LOGIN ? 'scripts/xray-shot-login.png' : 'scripts/xray-shot.png';
const EMAIL = 'zhihong@eternalgy.me'; // Chrome autofills the password once this is filled
// The control the replay clicks, matched on the name VISION gave it.
const ACT = LOGIN ? /log ?in|sign ?in|submit/i : /^macam yes$/i;
const LOGOUT = process.argv.includes('--logout'); // just log out and stop
const GEN = 'scripts/autocount-login.gen.mjs';

// ---------------------------------------------------------------- step 7: emit a PROGRAM
// The maps are data someone still has to interpret. This turns them into a
// lane-1 script that runs on selectors alone. No browser needed to do it.
if (process.argv.includes('--emit')) {
  const login = JSON.parse(fs.readFileSync('scripts/autocount-login.map.json', 'utf8'));
  const select = JSON.parse(fs.readFileSync('scripts/autocount.map.json', 'utf8'));
  const S = (map, re) => {
    const c = map.filter((e) => re.test(e.name.trim()));
    return (c.find((e) => /button|submit/i.test(e.role)) ?? c[0]).selector;
  };
  fs.writeFileSync(GEN, [
    '// PROTOTYPE — throwaway. Hardcoded, no error handling. Do not ship.',
    '// GENERATED by `node scripts/xray.mjs --emit`. Do not edit — re-emit instead.',
    '// Every selector below was compiled from a screenshot: vision named the control,',
    '// geometry matched that name to a real DOM box. Zero model calls at runtime.',
    "import { chromium } from 'patchright';",
    '',
    "const ctx = await chromium.launchPersistentContext('" + PROFILE.replace(/\\/g, '\\\\') + "', {",
    "  channel: 'chrome', headless: false, args: ['--no-sandbox'],",
    "  viewport: null, ignoreDefaultArgs: ['--enable-automation'],",
    '});',
    'const page = ctx.pages()[0] ?? (await ctx.newPage());',
    '',
    "console.log('step: goto');",
    "await page.goto('" + TARGET + "', { waitUntil: 'domcontentloaded' });",
    'await page.waitForTimeout(7000);',
    '',
    "if (page.url().includes('auth.')) {",
    "  console.log('step: log in');",
    "  await page.locator('" + S(login, /e-?mail|user/i) + "').fill('" + EMAIL + "');",
    '  await page.waitForTimeout(3000);',
    "  await page.locator('" + S(login, /log ?in|sign ?in|submit/i) + "').click();",
    '  await page.waitForTimeout(9000);',
    '}',
    '',
    "console.log('step: pick company');",
    "await page.locator('" + S(select, /^macam yes$/i) + "').click();",
    'await page.waitForTimeout(9000);',
    '',
    "console.log('IN:', page.url(), '|', await page.title());",
    'await ctx.close();',
    '',
  ].join('\n'));
  console.log('emitted', GEN);
  process.exit(0);
}

// ---------------------------------------------------------------- element table
// Runs in the page. Keeps an element only if hit-testing says it is really on
// top at its own centre -- no getComputedStyle guessing.
const TABLE_FN = () => {
  const path = (el) => {
    const parts = [];
    while (el && el.nodeType === 1 && el.tagName !== 'HTML') {
      const tag = el.tagName.toLowerCase();
      const sibs = [...el.parentNode.children].filter((s) => s.tagName === el.tagName);
      parts.unshift(sibs.length > 1 ? `${tag}:nth-of-type(${sibs.indexOf(el) + 1})` : tag);
      el = el.parentElement;
    }
    return parts.join('>');
  };
  const out = [];
  const all = document.querySelectorAll('input,button,a,select,textarea,img,label,[role],[onclick]');
  for (const el of all) {
    const r = el.getBoundingClientRect();
    if (r.width < 6 || r.height < 6) continue;
    if (r.bottom < 0 || r.top > innerHeight || r.right < 0 || r.left > innerWidth) continue;
    const cx = r.left + r.width / 2, cy = r.top + r.height / 2;
    const hit = document.elementFromPoint(cx, cy);
    if (!hit || !(hit === el || el.contains(hit))) continue;
    const near = el.closest('label')?.innerText || el.parentElement?.innerText || '';
    out.push({
      tag: el.tagName.toLowerCase(),
      type: el.getAttribute('type') || '',
      box: { x: Math.round(r.left), y: Math.round(r.top), w: Math.round(r.width), h: Math.round(r.height) },
      // never echo a password field's value to the terminal
      ownText: el.getAttribute('type') === 'password' ? '(hidden)'
        : (el.value || el.innerText || el.getAttribute('placeholder') || el.getAttribute('alt') || el.getAttribute('title') || '').trim().slice(0, 40),
      nearestLabelText: near.trim().slice(0, 40).replace(/\s+/g, ' '),
      selector: path(el),
    });
  }
  return { w: innerWidth, h: innerHeight, rows: out };
};

const ctx = await chromium.launchPersistentContext(PROFILE, {
  channel: 'chrome', headless: false, args: ['--no-sandbox'],
  viewport: null, ignoreDefaultArgs: ['--enable-automation'],
});
const page = ctx.pages()[0] ?? (await ctx.newPage());

try {
  console.log('step: goto', TARGET);
  await page.goto(TARGET, { waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(ARG_URL ? 12000 : 7000); // client-rendered pages need longer
  console.log('  landed:', page.url(), '|', await page.title());

  // The login page only exists while logged out. Get there by clicking the Log Out
  // control the FIRST map compiled -- lane 2 driving itself with its own output.
  if ((LOGIN || LOGOUT) && !page.url().includes('auth.')) {
    const prev = JSON.parse(fs.readFileSync('scripts/autocount.map.json', 'utf8'));
    const out = prev.find((e) => /log ?out|sign ?out/i.test(e.name));
    console.log(`step: log out via compiled selector "${out.name}" -> ${out.selector}`);
    await page.locator(out.selector).click();
    await page.waitForTimeout(9000);
    console.log('  landed:', page.url(), '|', await page.title());
  }
  // Log Out drops onto a confirmation page. Hop to the form the way a human does --
  // by clicking, not by typing a URL (buildplan section 8). Selector compiled by the run before.
  if ((LOGIN || LOGOUT) && page.url().includes('logout')) {
    const HOP = 'body>div>div>div>div>div:nth-of-type(3)>a'; // "Back to login"
    console.log('step: hop "Back to login" via compiled selector', HOP);
    await page.locator(HOP).click();
    await page.waitForTimeout(9000);
    console.log('  landed:', page.url(), '|', await page.title());
  }

  if (LOGOUT) {
    console.log('\nlogged out. stopping.');
  } else if (!NO_VISION) {
    // ---- step 1: arrival capture (screenshot + table at the same instant)
    console.log('\nstep 1: capture');
    await page.screenshot({ path: SHOT });
    const { w, h, rows } = await page.evaluate(TABLE_FN);
    console.log(`  viewport ${w}x${h} | ${rows.length} hit-tested visible elements`);
    for (const r of rows) console.log(`   ${String(r.tag + (r.type ? '[' + r.type + ']' : '')).padEnd(16)} ${String(r.box.x + ',' + r.box.y).padEnd(12)} ${String(r.box.w + 'x' + r.box.h).padEnd(10)} "${r.ownText}"  <- ${r.selector}`);

    // ---- step 2: vision pass (one call, on arrival, never per click)
    console.log('\nstep 2: vision');
    const { fastAsk, imageDataUrl } = await import('../dist/fastworker.js');
    const ans = await fastAsk(
      `Screenshot of a web page. List EVERY interactive control you can see: text fields, checkboxes, links, buttons.\n` +
      `One per line, exactly this format and nothing else:\nNAME | ROLE | x,y\n` +
      `x,y is the control's centre, normalised 0-1000. NAME is what a human would call it.`,
      // 3000 was not enough on a 28-control page: the reasoning consumed the whole
      // budget and the answer came back empty. Budget scales with page density.
      { images: [imageDataUrl(SHOT)], maxTokens: 8000, timeoutMs: 120_000 },
    );
    console.log(`  ${ans.ms} ms | ${ans.outputTokens} tok | reasoning ${ans.reasoningChars} chars`);
    console.log(ans.text.split('\n').map((l) => '   ' + l).join('\n'));

    // ---- step 3: correlate by geometry (the whole lane)
    console.log('\nstep 3: correlate');
    const map = [];
    for (const line of ans.text.split('\n')) {
      const m = line.match(/^\s*(.+?)\s*\|\s*(.+?)\s*\|\s*(\d+)\s*,\s*(\d+)/);
      if (!m) continue;
      const [, name, role, xs, ys] = m;
      const px = (+xs / 1000) * w, py = (+ys / 1000) * h;
      const hits = rows.filter((r) => px >= r.box.x && px <= r.box.x + r.box.w && py >= r.box.y && py <= r.box.y + r.box.h);
      if (!hits.length) { console.log(`   DROPPED  "${name}" at ${Math.round(px)},${Math.round(py)} — no element box contains that point`); continue; }
      hits.sort((a, b) => a.box.w * a.box.h - b.box.w * b.box.h);
      const hit = hits[0];
      console.log(`   "${name}" -> ${hit.selector}   (box ${hit.box.x},${hit.box.y} ${hit.box.w}x${hit.box.h})`);
      map.push({ name, role, selector: hit.selector, box: hit.box, capturedAt: new Date().toISOString(), url: page.url() });
    }

    // ---- step 4: emit
    fs.writeFileSync(MAP, JSON.stringify(map, null, 2));
    console.log(`\nstep 4: wrote ${MAP} — ${map.length} controls`);
  } else {
    // ---- step 5: prove the compile. Selectors only. No model, no screenshot, no names.
    console.log('\nstep 5: replay from map, ZERO model calls');
    const map = JSON.parse(fs.readFileSync(MAP, 'utf8'));

    // step 6: do the emitted selectors still resolve after a fresh page load?
    const resolved = await page.evaluate((m) => m.map((e) => ({
      name: e.name,
      n: document.querySelectorAll(e.selector).length,
      text: (document.querySelector(e.selector)?.innerText || '').trim().slice(0, 20),
    })), map);
    for (const r of resolved) console.log(`  ${r.n === 1 ? 'OK  ' : 'FAIL'} "${r.name}" -> ${r.n} match, DOM text "${r.text}"`);

    const cands = map.filter((e) => ACT.test(e.name.trim()));
    const target = cands.find((e) => /button|submit/i.test(e.role)) ?? cands[0];
    if (!target) { console.log('\n  no ACT match on this map — survival check only, nothing clicked'); await ctx.close(); process.exit(0); }
    const before = { url: page.url(), title: await page.title() };
    if (LOGIN) {
      const email = map.find((e) => /e-?mail|user/i.test(e.name));
      console.log(`\n  fill "${email.name}" via ${email.selector}`);
      await page.locator(email.selector).fill(EMAIL);
      await page.waitForTimeout(3000); // give Chrome a moment to autofill the password
    }
    console.log(`  click "${target.name}" via ${target.selector}`);
    await page.locator(target.selector).click();
    await page.waitForTimeout(9000);
    await page.screenshot({ path: 'scripts/xray-after.png' });

    console.log(`\n  before: ${before.url}  |  ${before.title}`);
    console.log(`  after : ${page.url()}  |  ${await page.title()}`);
  }
} catch (err) {
  console.error('\nDIED at', page.url(), '\n', err.message);
  await page.screenshot({ path: 'scripts/xray-crash.png' }).catch(() => {});
} finally {
  await ctx.close();
}
